version: "3.10"

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./colab_data:/app/colab_data
      - ./chroma_db:/app/chroma_db
    environment:
      - DEEPINFRA_API_KEY="APIKEY"
      - GROQ_API_KEY="APIKEY"
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
      - ollama 


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

volumes:
  ollama_data: